name: SimpleStats
version: 1.0.1
main: com.xlilith.simplestats.Main
api-version: 1.21.1
author: xLilith99
description: Plugin básico para las estadísticas de los usuarios
commands:
  simplestats:
    description: Recarga los placeholders de SimpleStats
    usage: /simplestats reload
    permission: simplestats.reload
    permission-message: "No tienes permiso para ejecutar este comando."
